const TOP_ZONE_SIZE = .1

const MONSTER_ZONE_SIZE = .65
const TANK_ZONE_SIZE = .15
const BOTTOM_ZONE_SIZE = .1

const TANK_BODY_WIDTH = .1
const TANK_BODY_HEIGHT = .5

const TANK_GUN_WIDTH = .03
const TANK_GUN_HEIGHT = 3

const TANK_SPEED = 3

const BULLET_SPEED = 30
const BULLET_SIZE = 5

const MONSTER_WIDTH = .3
const MONSTER_HEIGHT = .5

const MONSTER_HIT_BOX_WIDTH = MONSTER_WIDTH * .5
const MONSTER_HIT_BOX_HEIGHT = .4 

const START_HIT_SIZE = BULLET_SIZE
const MAX_HIT_SIZE = 60

const START_TEXT_HIT_SIZE = 60
const MAX_TEXT_HIT_SIZE = 100

const HIT_EFFECT_DURATION = 500


const HP_BAR_HEIGHT = .03

const MONSTER_START_HP = 1000
const TANK_START_DMG = 1

const MONSTER_PER_STAGE = 10

const MONSTER_RESET_TIME = 1000